spring:
  profiles:
    active: dev
  security:
    user:
      name: root
      password: 123456

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  jwt:
    secret: 'JWTSECRET'
    expiration: 86400000 # 24小时
    token-header: 'Authorization'
    token-schema: 'Bearer'

  redis:
    database: mall
    key:
      admin: 'ums:admin'
      resourceList: 'ums:resourceList'
    expire:
      common: 86400 # 24小时

  secure:
    ignored:
      urls: #安全路径白名单
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.ico
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /admin/login
        - /admin/register
        - /admin/info
        - /admin/logout
        - /minio/upload
